"""Build a mapping figure-name -> generating-code for the Quarto site.

Walks every *.ipynb in the repo (chap*.ipynb plus older auxiliary
notebooks), extracts the source of any code cell that produces a
figure_*.png file.  Two filename patterns are recognised:

    1) Full literal:                'figure_foo.png'
    2) String concatenation:        'figure_foo' + '.png'

Writes the mapping as a JS payload (figure_code_map.js) to be loaded
verbatim from the rendered site (and consumed by inject_figure_tabsets.py).

Run from the repo root:

    python3 tools/build_figure_code_map.py .
"""
from __future__ import annotations
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# Pattern A: a full filename appearing as one literal token.
FIG_FULL = re.compile(
    r"figure_[A-Za-z0-9_\-.]+\.(?:png|jpg|jpeg|gif|svg)",
    re.IGNORECASE,
)

# Pattern B: 'figure_foo' + '.png'  (two literals joined by + with optional whitespace).
FIG_SPLIT = re.compile(
    r"""['"](figure_[A-Za-z0-9_\-]+)['"]\s*\+\s*['"]\.(png|jpg|jpeg|gif|svg)['"]""",
    re.IGNORECASE,
)

# Notebooks to skip (utility / scratch / legacy export with no useful prose).
SKIP_FILES = {
    "test_util.ipynb",
}


def figures_in(text: str) -> List[str]:
    found: List[str] = []
    for m in FIG_FULL.finditer(text):
        found.append(m.group(0))
    for m in FIG_SPLIT.finditer(text):
        found.append(f"{m.group(1)}.{m.group(2).lower()}")
    # de-dup but preserve insertion order
    seen = set()
    out = []
    for f in found:
        if f not in seen:
            seen.add(f); out.append(f)
    return out


def collect_cells(repo: Path) -> List[Tuple[str, int, str]]:
    """(notebook, cell_index, code_source) for every code cell in every
    .ipynb at repo root."""
    out: List[Tuple[str, int, str]] = []
    for nb_path in sorted(repo.glob("*.ipynb")):
        if nb_path.name in SKIP_FILES:
            continue
        try:
            nb = json.loads(nb_path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"  [skip] {nb_path.name}: {exc}", file=sys.stderr)
            continue
        for i, cell in enumerate(nb.get("cells", [])):
            if cell.get("cell_type") != "code":
                continue
            src = cell.get("source")
            if isinstance(src, list):
                src = "".join(src)
            if not src or not src.strip():
                continue
            out.append((nb_path.name, i, src))
    return out


def build_map(cells: List[Tuple[str, int, str]]) -> Dict[str, dict]:
    """Map figure_name -> {notebook, cell, code}.

    First-occurrence wins.  chap*.ipynb is preferred over auxiliary
    notebooks so the user-facing book gets canonical sources.
    """
    # Sort so chap*.ipynb come first, then everything else alphabetically.
    def order_key(c):
        nb = c[0]
        return (0 if re.match(r"chap\d+\.ipynb$", nb) else 1, nb, c[1])
    cells = sorted(cells, key=order_key)

    mapping: Dict[str, dict] = {}
    for nb_name, idx, code in cells:
        for fig in figures_in(code):
            if fig in mapping:
                continue
            mapping[fig] = {
                "notebook": nb_name,
                "cell": idx,
                "code": code.rstrip(),
            }
    return mapping


def write_js(mapping: Dict[str, dict], out_path: Path) -> None:
    payload = json.dumps(mapping, ensure_ascii=False, indent=2)
    out_path.write_text(
        "/* AUTOGENERATED by tools/build_figure_code_map.py */\n"
        f"window.__figureCodeMap = {payload};\n",
        encoding="utf-8",
    )


def main(repo_root: Path) -> None:
    cells = collect_cells(repo_root)
    notebooks = sorted({nb for nb, _, _ in cells})
    mapping = build_map(cells)
    out = repo_root / "figure_code_map.js"
    write_js(mapping, out)
    print(f"Scanned {len(cells)} code cells across {len(notebooks)} notebooks: {notebooks}")
    print(f"Mapped {len(mapping)} figure(s)")
    # Show a per-notebook breakdown for diagnostics
    by_nb: Dict[str, int] = {}
    for v in mapping.values():
        by_nb[v["notebook"]] = by_nb.get(v["notebook"], 0) + 1
    for nb, n in sorted(by_nb.items()):
        print(f"  {nb:50s}  {n:3d} figure(s)")
    print(f"Written: {out.relative_to(repo_root)}")


if __name__ == "__main__":
    main(Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve())
